src/config/ini_config.asciidoc, src/gui/axis.asciidoc
Docs for ini_config and axis updated to reflect
additional settings available following recent
commit to main repo with same
Signed-off-by: Mick Grant <arceye@mgware.co.uk>
=> Update src docs for Axis Gui Additional features

src/gui/axis.asciidoc
=> Tidy up Axis GUI additions

src/gui/axis.asciidoc
As discussed
Add existing pins and additional pin from recent commit
Appear not to be documented elsewhere
=> Add axisui pins to Axis documentation

README.asciidoc, src/common/python-interface.asciidoc
@luminize   Just testing out editing docs.  Nice work! Pretty straight forward!
=> Fixed Typo in readme

README.asciidoc, machinekit-documentation/documents-index.asciidoc, machinekit-documentation/getting-help.asciidoc
instructions on how to correctly get help when getting into trouble
=> instruction: how to frame a proper support question

machinekit-documentation/getting-help.asciidoc
=> work on getting-help.asciidoc

machinekit-documentation/documents-index.asciidoc, machinekit-documentation/getting-help.asciidoc, machinekit-documentation/setting-up/lineardelta-FDM-printer.asciidoc
Update of some (anchor) links and general typos
=> Getting help

src/remap/structure.asciidoc
fixes https://github.com/machinekit/machinekit-docs/issues/24
closes https://github.com/machinekit/machinekit-docs/issues/24
=> remap/structure.asciidoc: fix remap list for M100-M999

machinekit-documentation/developing/machinekit-developing.asciidoc, machinekit-documentation/documentation-matrix.asciidoc, machinekit-documentation/index-HAL.asciidoc, machinekit-documentation/index-developer.asciidoc
Tidy up plus a full list of package dependencies for building on Jessie
=> Further cross indexing and additions under development and HAL components

src/gui/gladevcp.asciidoc
Signed-off-by: Norbert Schechner <nieson@web.de>
=> gladevcp - iconview - update documentation to include new signal

src/common/python-interface.asciidoc
=> Correct rebranding errors related to linuxcnc python module

machinekit-documentation/getting-started/APT-packages-jessie.asciidoc, machinekit-documentation/getting-started/APT-packages-wheezy.asciidoc
update instructions for apt-repository
=> apt-packages-*: update machinekit apt repository instruction

machinekit-documentation/developing/developing.asciidoc, machinekit-documentation/developing/machinekit-developing.asciidoc, machinekit-documentation/getting-started/APT-packages-jessie.asciidoc, machinekit-documentation/getting-started/APT-packages-wheezy.asciidoc
takeover building instructions from machinekit.io
=> Building instructions from site

machinekit-documentation/developing/machinekit-developing.asciidoc
`to add RT-PREEMPT support, add a 'p'` --> `to add RT-PREEMPT support, add a 'r'`
=> Typo in line 53

src/hal/comp.asciidoc, src/hal/instcomp.asciidoc
Add new options to produce both asciidoc and groff man pages
Minor edits and info.
=> Update comp & instcomp docs

_includes/analytics.html
so preview results are not measured
=> analytics.html: include only if production site is built

_config.yml, _includes/sandbox.html, _includes/search-bar.html, docs/developing/CAN-developing.asciidoc, docs/developing/building-rt-preempt-kernel.asciidoc, docs/developing/developing.asciidoc, docs/developing/machinekit-developing.asciidoc, docs/developing/writing-components.asciidoc, docs/gui/gmoccapy.asciidoc, docs/hal/components.asciidoc, docs/hal/intro.asciidoc, docs/hal/tutorial.asciidoc, docs/install/Latency_Test.asciidoc, docs/setting-up/CAN-developing-setup.asciidoc, googlefe8e1e0739168a82.html, index.html, search-result.html
Remove old google search tag
Edit all absolute URLs to preview.machinekit.io, to machinekit.io
=> New CSE preparation

_includes/search-bar.html, index.html, search-result.html
=> New search engine refs for site

_config.yml, docs/common/Getting_Machinekit.asciidoc, docs/common/UnifiedBuild.asciidoc, docs/config/ini_config.asciidoc, docs/config/pncconf.asciidoc, docs/developing/CAN-developing.asciidoc, docs/developing/building-rt-preempt-kernel.asciidoc, docs/developing/developing.asciidoc, docs/developing/machinekit-developing.asciidoc, docs/developing/writing-components.asciidoc, docs/drivers/pluto_p.asciidoc, docs/gcode/gcode.asciidoc, docs/gui/gladevcp.asciidoc, docs/gui/gmoccapy.asciidoc, docs/hal/components.asciidoc, docs/hal/intro.asciidoc, docs/hal/parallel_port.asciidoc, docs/hal/tutorial.asciidoc, docs/install/Latency_Test.asciidoc, docs/man/man9/hostmot2.9.asciidoc, docs/motion/tweaking_steppers.asciidoc, docs/quickstart/stepper_quickstart.asciidoc, docs/setting-up/CAN-developing-setup.asciidoc, docs/source-highlight/ngc.lang, scripts/repl.sh, src/index.tmpl, src/index_fr.tmpl
let's see how this comes out on preview
I temporarily enabled the linkchecker on the preview job
=> Relative links - test PR

docs/sandbox/index.asciidoc
Edited for brevity and include link to asciidoc guide
=> Update to SandBox blurb

Makefile
@ArcEye  - would you look into scripts/filenum such it does not touch or regenerate files if not needed?
all updates - needed or not - go against preview delay
=> Makefile: minimal rebuild - dont touch asciidoc files if not necessary

docs/site/about-this-site.asciidoc
just having a look - not yet linked in (where?)
=> docs/site/about-this-site: first cut

docs/site/about-this-site.asciidoc
or they can never be previewed
=> do not overspecify intra-site URI's

docs/getting-started/install-rt-kernel-RPi2.asciidoc
Add info about RPi models, that work with this. These are the models RPi 2 and RPi 3.
=> Add RPi 2/3

docs/gui/axis-machinekit-enhancements.asciidoc, docs/gui/axis.asciidoc
Add specific doc covering enhancements made to Axis in Machinekit
and add links in existing Axis docs
=> Fully document Axis GUI enhancements

docs/gui/gladevcp.asciidoc
=> some repair on gladevcp.asciidoc

docs/hal/basic_hal.asciidoc
Per https://github.com/machinekit/machinekit/issues/959
=> basic_hal.asciidoc: now correctly documents 64 bit floats

_config.yml, docs/documenting/diagram-examples.asciidoc
This will probably give errors. `jekyll-plantuml` needed to be installed. We'll see :)
=> diagram-examples.asciidoc: add PlantUML examples

scripts/index-gen.sh
=> Add footnote to generated index, that pages available from package too.

docs/man/man9/motion.asciidoc
Reverts machinekit/machinekit-docs#203
=> Revert "motion.asciidoc: recommit changes to motion component"

docs/man/man1/halcmd.asciidoc, docs/man/man1/halmeter.asciidoc
That will teach me to idly browse the website!
=> Remove inline troff formatting and other rubbish.

docs/man/man1/axis-remote.asciidoc, docs/man/man1/axis.asciidoc, docs/man/man1/comp.asciidoc, docs/man/man1/gs2.asciidoc, docs/man/man1/hal_input.asciidoc
=> Further de-troffing, /docs/man1 components

docs/man/man1/gladevcp.asciidoc, docs/man/man1/halcmd.asciidoc, docs/man/man1/halmeter.asciidoc, docs/man/man1/halrun.asciidoc, docs/man/man1/halsampler.asciidoc, docs/man/man1/halstreamer.asciidoc
=> De-troff further /docs/man1 pages, update and make more readable

docs/developing/machinekit-developing.asciidoc, docs/getting-started/install-runtime-packages.asciidoc
=> Amend documentation to cover machinekit-manual-pages package

docs/man/man9/stepgen.asciidoc
=> Minor edit - remove spurious highlight in synopsis

docs/man/man3/PM_ROTATION_VECTOR.asciidoc, docs/man/man3/hal_add_funct_to_thread.asciidoc, docs/man/man3/hal_create_thread.asciidoc, docs/man/man3/hal_exit.asciidoc, docs/man/man3/hal_export_funct.asciidoc, docs/man/man3/hal_init.asciidoc, docs/man/man3/hal_malloc.asciidoc, docs/man/man3/hal_param_new.asciidoc, docs/man/man3/hal_parport.asciidoc, docs/man/man3/hal_pin_new.asciidoc, docs/man/man3/hal_ready.asciidoc, docs/man/man3/hal_set_lock.asciidoc, docs/man/man3/hal_signal_new.asciidoc, docs/man/man3/hal_start_threads.asciidoc, docs/man/man3/hal_type_t.asciidoc
Remove various troff fragments
=> Re-format /man3 PM_ and hal_ documents for readability.

docs/man/man3/hm2_allocate_bspi_tram.asciidoc, docs/man/man3/hm2_bspi_set_read_function.asciidoc, docs/man/man3/hm2_bspi_set_write_function.asciidoc, docs/man/man3/hm2_bspi_setup_chan.asciidoc, docs/man/man3/hm2_bspi_write_chan.asciidoc, docs/man/man3/hm2_pktuart_read.asciidoc, docs/man/man3/hm2_pktuart_send.asciidoc, docs/man/man3/hm2_pktuart_setup.asciidoc, docs/man/man3/hm2_tram_add_bspi_frame.asciidoc, docs/man/man3/hm2_uart_read.asciidoc, docs/man/man3/hm2_uart_send.asciidoc, docs/man/man3/hm2_uart_setup.asciidoc
=> Reformat and clean up all man3/hm2_ manual pages

docs/man/man1/axis.asciidoc
=> Additional info re pins added to axis manual page

docs/hal/instcomp.asciidoc
Was largely there bar a couple of specifics.
=> Update instcomp documentation post multicore merge

Makefile
machinetalk-protobuf/pull/75 should have fixed the problem
=> Revert changes to Makefile to prevent document build

docs/commercial-support/index.asciidoc
See https://github.com/machinekit/machinekit-docs/issues/253
=> adding myself to commercial support

docs/getting-started/install-rt-kernel-amd64.asciidoc, docs/getting-started/install-rt-kernel-i386.asciidoc
=> Amend docs to reflect availability of backported rt kernels in Jessie

docs/developing/qtquickvcp.asciidoc
Correct the link to desktop clients.
=> Link to desktop clients returns a 404.

_includes/forum-search.html, _includes/header.html, _includes/primary-nav-items2.html, _includes/search-bar.html
Add Forum search, by appending search string to preset search url and creating separate search box.
Spend hours buggering about trying to get them to line up properly!
=> Change google search to plain input box to get rid of clunky branding.

_includes/document-search.html, _includes/forum-search.html, _includes/primary-nav-items2.html, _includes/search-radio.html
Unused files left in for reference.
Whole page could do with laying out properly in css instead of
html grids as present, to get all elements aligned correctly,
but will do for now.
=> Change search to single selectable input which displays in same tab.

docs/getting-started/getting-started-platform.asciidoc
from Google Groups Machinekit posts
=> Add link to example Debian install

docs/developing/develop-index.asciidoc, docs/hal/basic_hal.asciidoc, docs/hal/threads-and-latency.asciidoc, docs/man/man1/halcmd.asciidoc, docs/man/man9/threads.asciidoc
Then link to new threads and latency doc.
=> Add info on newthread command where missing.

community/channels.asciidoc
Updating How to discuss Machinekit to include Matrix Room. Also added the differentiation between Machinekit-HAL and Machinekit-CNC.
=> Adding the Matrix room

docs/developing/machinekit-developing.asciidoc
Update documentation about how to build Machinekit-HAL (and to lesser end Machinekit-CNC) in light of new flavour system.
=> Update documentation to new build rules

docs/developing/machinekit-developing.asciidoc
This pull request updates the documentation to be in sync with the latest changes introduced in machinekit/machinekit-hal#288 - Rework of buildsystem, part 5.
Of course, this is still _slapping a lipstick on a pig_ situation.
=> Update documentation for changes in buildsystem flow
