machinekit/machinekit-docs

- src/config/ini_config.asciidoc
Bas, 
This is addition to docs to cover recent merge of user defined arc tolerance field in ini file
https://github.com/machinekit/machinekit/commit/3fc784d664afe2df067728d1b0eae7aa041a513a
refers
regards
> Add Arc Tolerance ini file field notes to ini_config doc sources

- src/Makefile
- src/Submakefile
- src/common/UnifiedBuild.asciidoc
machinekit/machinekit#327, which silences compile warnings, fixed
several warnings in the `/docs` directory. Documentation was split
into the 'machinekit-docs' repo before the PR was merged.
These are the changes that would have followed the documentation side
of the split.
Fixes #8.
>  Pick pre-split commits from the 'Silence compile warnings' PR

- machinekit-documentation/documentation-matrix.asciidoc
- machinekit-documentation/setting-up/lineardelta-FDM-printer.asciidoc
- machinekit-documentation/setting-up/setting-up-examples.asciidoc
Set-up instructions focussing on calibrating the mechanics of a linear delta type machine. In the same time getting a new user thru some steps (terminal) and concepts (HAL) with links to other parts of the documentation.
Special care was taken not to focus on platform or 3D FDM/FFF printing alone. This can be done in other possibly future documents.
> setting-up documentation of a linear delta type machine

- machinekit-documentation/developing/machinekit-developing.asciidoc
`./configure`  needs explicit options as otherwise Xenomai kernel modules are also built.
Like:
```
LD [M]  /home/cml/machinekit-build-test/src/objects/xenomai-kernel/3.8-1-xenomai.x86-amd64/wcomp.ko
LD [M]  /home/cml/machinekit-build-test/src/objects/xenomai-kernel/3.8-1-xenomai.x86-amd64/wcompn.ko
LD [M]  /home/cml/machinekit-build-test/src/objects/xenomai-kernel/3.8-1-xenomai.x86-amd64/weighted_sum.ko
LD [M]  /home/cml/machinekit-build-test/src/objects/xenomai-kernel/3.8-1-xenomai.x86-amd64/xhc_hb04_util.ko
LD [M]  /home/cml/machinekit-build-test/src/objects/xenomai-kernel/3.8-1-xenomai.x86-amd64/xor2.ko
```
That is at least confusing.
Tested on  wheezy:
```
cml@debian-cml2:~/machinekit-build-test$ uname -a
Linux debian-cml2 3.8-1-xenomai.x86-amd64 #1 SMP Debian 3.8.13-9 x86_64 …
```
> amd64 configure needs explicit options as for now

- machinekit-documentation/developing/machinekit-developing.asciidoc
Without `pkg-config`:
```
~/machinekit/src$ ./autogen.sh
configure.ac:30: error: possibly undefined macro: AC_MSG_ERROR
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
configure.ac:92: error: possibly undefined macro: AC_DEFINE
configure.ac:95: error: possibly undefined macro: AC_SUBST
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
Tested on:
```
~/machinekit/src$ uname -a
Linux debian 3.8-1-xenomai.x86-amd64 #1 SMP Debian 3.8.13-12~1jessie~1da x86_64 GNU/Linux
```
See also: http://stackoverflow.com/a/9024469/4599792
> Add pkg-config to the list of supporting packages

- docs/developing/develop-index.asciidoc
- docs/documenting/documenting.asciidoc
- docs/documenting/updating-your-fork.asciidoc
I wish there'd be a way to find out which links are js-generated so they can be submitted to the checker
> fix links not detected by linkchecker

- _includes/css/style.css
Existing style rendered backgrounds in muddy grey with black test,
which made for difficult reading.
Tables and Warnings were particularly bad
All graphic text backgrounds changed to a high contrast pale violet.
[NOTE] colours changed to a more restful pale blue
[WARNING] upgraded to the same type of banner as [NOTE] with muted red
background
To see all above plus [source] highlighting, see
preview.machinekit.io/docs/config/ini_config
which contains the lot.
Goes a long way to fix #144
> Modify style sheet to achieve proper contrast between text and bgrnd

- docs/common/starting-emc.asciidoc
- docs/drivers/hostmot2.asciidoc
- docs/getting-started/getting-started-platform.asciidoc
- docs/getting-started/installing-packages.asciidoc
- docs/gui/ngcgui.asciidoc
- docs/gui/tooledit.asciidoc
- docs/hal/basic_hal.asciidoc
- docs/hal/parallel_port.asciidoc
- docs/ladder/classic_ladder.asciidoc
- docs/quickstart/stepper_quickstart.asciidoc
A peculiar issue with this method of asciidoc to html conversion
in respect of [NOTE]
If the admonition block favoured by asciidoctor is used
```
[NOTE]
====
Text in here
====
```
It will be rendered in a white foreground, which is very difficult to read.
If however it is written as per asciidoc, which the legacy docs are
```
[NOTE]
Text here
```
The text is rendered in a black foreground and easily legible
A third method used in some legacy docs fails to render properly
with everything after a blank line omitted and
back in the page text again
```
[NOTE]
//__=================================
Big block of text
Another block of text
//__================================
```
Various docs edited to make NOTE banners easily legible and ensure
the text intended to be displayed in them is so …
> Fix visibility of some [NOTE] banners

- docs/hal/halui_examples.asciidoc
- docs/hal/pyvcp.asciidoc
- docs/hal/pyvcp_examples.asciidoc
I fixed missing images by updated the imagesdir and imagesoutdir vars to match known working pages in the docs.
> Image path fix in hal docs

- docs/documenting/diagram-examples.asciidoc
hm, somehow we should avoid creating branches in this repo
> diagrams: make wavedrom use svg instead of png, link to article

- _includes/docs_contents.html
- _includes/primary-nav-items.html
- index.html
(top of page)
Remove side bar and front page implementations
Fixes [machinekit/machinekit.github.io] Search Bar on top of page (#60)
> Move Search-Bar to primary navigation items for all pages

- docs/infra/repositories.asciidoc
Used as menu link in docs sidebar and needed to be shorter
> Capitalise and shorten top level header title

- _includes/docs_contents.html
Now that searches are fully seeded, there are a lot of hits coming
from crawlers finding 'boiler plate' sidebar links and including
those
eg. Search `HAL` and the `Hal Utilities and GUIs` link keeps appearing.
First stage is to wrapper in a 'nocontent' div
Once in place I can change the cse.xml to activate it and eventually
the crawlers will exclude it on new crawls.
> Amend docs_contents to exclude from google searches

- _includes/docs_contents.html
- _includes/edit-me.html
- _includes/primary-nav-items.html
- _includes/sandbox.html
onto same line as `Search`
The increase in RH sidebar items has pushed these items further down
the page
Moving them makes the layout more coherent, sidebar is for quick access
links to major topics
The navigation list keeps 'Edit this page' in particular, immediately
available and obvious from any page in the site
> Move `Edit This Page` and `Sandbox` links to navigation area

- docs/man/man3/hm2_pktuart_read.asciidoc
Some pieces of the previous manpage code did not render properly.
Do not know if any *asciidoc* format for functions was agreed upon, so let it be a proposal.
> Adjusting format

- _includes/css/style.css
in order to avoid lines running over their `<div>` containers.
Simple example: http://www.w3schools.com/cssref/tryit.asp?filename=trycss3_word-wrap
> Insert word-wrap: break-word into article definition

- docs/man/man9/motion.asciidoc
due to the takeover of manpages from machinekit/machinekit to machinekit/machinekit-docs the original commit https://github.com/machinekit/machinekit/commit/153e2513e311784f1ca8a09e16dabbab8ae40455 got lost.
> motion.asciidoc: recommit changes to motion component

- docs/man/man3/hal_pin_new.asciidoc
Functions signatures were overrunning before.
> Test word wrapping for normal text and code.

- docs/getting-started/APT-packages-raspbian.asciidoc
- docs/getting-started/installing-packages.asciidoc
Displays info for setting /etc/apt/sources.list.d/machinekit.list
to the 'jessie' repo
Should be the 'raspbian' repo
As reported by user jtheath@gmail.com
> Correct 'Getting Started' section regards raspbian packages

- docs/hal/tools.asciidoc
- docs/man/man1/halcmd.asciidoc
Added documentation for the "newthread" command to halcmd man page.  Also changes some outdated notes about manpages, and documented the use of "mank" instead of "man" to read them.
> update halcmd man page

- docs/man/man1/machinekit.1
- scripts/man-stubs.sh
To be used within Jenkins website-production job to create symlinks
and package them for installation into /usr/share/man
After installation all `man <component>` commands, where `<component>`
is a Machinekit component with a manual page, will be diverted to
an informational stub showing how to access the manual page.
From https://github.com/machinekit/machinekit-docs/pull/216#issuecomment-238416862
by @cdsteinkuehler 
> Man page stub & script to create links to it for each manual page

- scripts/man-stubs.sh
fpm used in jenkins to create packages, does not seem to work with
file globs, only individual files or complete dirs
Need man-stubs to be able to be scripted with an arg,
to create a dir in the Jenkins workspace to hold the links,
so they can be passed to fpm as directory addresses
> Amend man-stubs script

- docs/man/man9/threads.asciidoc
PR 1026 in machinekit replaces the threads component with "newthread" command.
This PR updates machinekit-docs to match.
> threads component is deprecated

- docs/man/man9/classicladder.asciidoc
- docs/man/man9/delayline.asciidoc
- docs/man/man9/encoder.asciidoc
- docs/man/man9/encoder_ratio.asciidoc
- docs/man/man9/gantrykins.asciidoc
- docs/man/man9/gladevcp.asciidoc
- docs/man/man9/hal_pru_generic.asciidoc
- docs/man/man9/hm2_7i43.asciidoc
- docs/man/man9/hm2_pci.asciidoc
- docs/man/man9/hostmot2.asciidoc
- docs/man/man9/kins.asciidoc
- docs/man/man9/lcd.asciidoc
- docs/man/man9/lineardeltakins.asciidoc
- docs/man/man9/matrix_kb.asciidoc
The first few ones at least were largely OK.
Mostly edited for consistency of formatting and appearence
plus a couple of factual updates, instances of 'Linuxcnc',  occasional stray troff formatting etc
> Tidy and format /man9 components

- docs/man/man3/intro_hal.asciidoc
- docs/man/man3/intro_rtapi.asciidoc
- docs/man/man3/rtapi_app_exit.asciidoc
- docs/man/man3/rtapi_app_main.asciidoc
- docs/man/man3/rtapi_clock_set_period.asciidoc
- docs/man/man3/rtapi_delay.asciidoc
- docs/man/man3/rtapi_div_u64.asciidoc
- docs/man/man3/rtapi_exit.asciidoc
- docs/man/man3/rtapi_get_time.asciidoc
- docs/man/man3/rtapi_init.asciidoc
- docs/man/man3/rtapi_module_param.asciidoc
- docs/man/man3/rtapi_mutex.asciidoc
- docs/man/man3/rtapi_outb.asciidoc
- docs/man/man3/rtapi_print.asciidoc
- docs/man/man3/rtapi_prio.asciidoc
- docs/man/man3/rtapi_region.asciidoc
- docs/man/man3/rtapi_set_msg_level.asciidoc
- docs/man/man3/rtapi_shmem.asciidoc
- docs/man/man3/rtapi_snprintf.asciidoc
- docs/man/man3/rtapi_task_new.asciidoc
- docs/man/man3/rtapi_task_pause.asciidoc
- docs/man/man3/rtapi_task_start.asciidoc
- docs/man/man3/rtapi_task_wait.asciidoc
Several corrections to obvious errors, but probably wrong elsewhere too
Thats it, I am finished with manual pages!
> Re-format /man/man9 rtapi_ for readability and remove troff

- docs/developing/machinekit-developing.asciidoc
Current instructions take no account of other installed versions and
are unnecessarily convoluted just to write a few lines to a file.
> Clarify instructions for setting RIP env vars

- docs/remap/structure.asciidoc
Add docs for remapping new codes `M62`-`M66` (MK PR 957 [1]) and `M19`
(MK PR 1031 [2])
[1]: https://github.com/machinekit/machinekit/pull/957
[2]: https://github.com/machinekit/machinekit/pull/1031
> remap/structure.asciidoc:  add new existing codes

- docs/hal/instcomp.asciidoc
Tidies up from changes in #1095
> Remove references to deprecated singleton instantiated components

- docs/config/pncconf.asciidoc
- docs/config/stepconf.asciidoc
Required to test system is properly installed but also to
ensure there has been one running of the linuxcnc
script before stepconf/pncconf is run, to ensure the `~/machinekit`
path is valid
> Add note to stepconf and pncconf docs advising sim run first.

- docs/hal/instcomp.asciidoc
Docs show delimiter as `---` but code has `--`
> Correct extra args delimiter

- docs/code/Contributing-to-Machinekit.asciidoc
- docs/getting-started/install-runtime-packages.asciidoc
- docs/hal/comp.asciidoc
This was deprecated in PR #1230
> Remove references to installing separate machinekit-dev package.

- _config.yml
- _layouts/default.html
GA has been added previously but was not active to a typo in the Jekyll configuration.
> Enable Google Analytics

- docs/getting-started/machinekit-images.asciidoc
Steer beginners to the 3.8 kernel image until they can grasp the issues
involved in using a later image.
(Or until someone produces a simple guide to using them)
> Interim clarification on BBB SD card images

- _includes/search-bar.html
Google have moved to v2 of their CSE which of course is
completely incompatible with our present v1, so currently
searches don't work.
This just inserts a default GCSE search box, which works and
renders a new page with results.
When time allows will revisit and try to make it prettier:)
> Fix broken Google Custom Search Engine

- _includes/primary-nav-items2.html
Rendering was different in Opera, so presumably Chrome, Vivaldi and any other Chrome based browser
This fills the top line so they have both search boxes in second line, as Firefox did anyway
> Add Forum link to ensure display same in different browsers

- docs/getting-started/install-rt-kernel-amd64.asciidoc
- docs/getting-started/install-rt-kernel-i386.asciidoc
- docs/getting-started/install-runtime-packages.asciidoc
Specifically that Stretch does not provide packages or kernels for Xenomai
> Clarify the availability of Xenomai packages and kernels in the repo

- _config.yml
- _includes/head.html
If you use google analytics, despite in effect giving them all your
site traffic data for free, in return for a rehashed view of it,
you are counted as the 'data controller'.
Even the retention of accessing IP addresses is regarded
as personal information.
Safest thing for now is to suspend use until assessed as compliant,
or consider discontinuance if of no practical benefit.
> Pause google analytics usage until its compliance with GDPR is verified.

- _includes/forum-search.html
- _includes/primary-nav-items.html
- _includes/primary-nav-items2.html
- _includes/search-bar.html
Google has seamlessly removed a directory level from the path to their search engine,
rendering our searches that use it useless.
Hopefully will restore.
> Get rid of google CSE and do search that works.

- docs/hal/threads-and-latency.asciidoc
- docs/man/man1/halcmd.asciidoc
Add new page about HAL threads and latency.
The `newthread` command seems to be undocumented outside of the brief
description `docs/man/man1/halcmd.asciidoc`.  This page serves as a
stub for more in-depth documentation on threads and latency topics,
and documents the `newthread cgname=/rt` argument.
Also `cgname=/rt` arg to halcmd(1) man page.
See machinekit/machinekit#1426
> Document `newthread cgname=/rt`

- docs/man/man3/hm2_bspi_setup_chan.asciidoc
Signed-off-by: Michael Brown <producer@holotronic.dk>
doc update to reflect PR https://github.com/machinekit/machinekit-hal/pull/213
> Update hm2_bspi_setup_chan parameters

- .github/workflows/build-preview-pages.yaml
- .github/workflows/ping-remote-repository.yaml
This will build Machinekit.io site as an artifact (downloadable) on opening pull request to master branch and on push to any other branch. On push to master branch it will also signal remote repository $GITHUBUSER/machinekit.github.io.
> Build Machinekit site preview and signal remote repository

- docs/developing/machinekit-developing.asciidoc
Upgraded documentation how to build Machinekit-HAL and Machinekit-CNC RIP.
Added information on how to use Docker container to build Debian packages.
> Update stale information on building Machinekit-HAL/Machinekit-CNC

- .github/workflows/build-preview-pages.yaml
In GitHUB Actions workflow, use first non-merge commit for metadata generation.
Instead of non-working, convoluted and nonsense current solution.
> Just use first non-merge commit

- docs/developing/common-developing.asciidoc
- docs/developing/developing.asciidoc
- docs/developing/emcapplication-developing.asciidoc
- docs/developing/machinekit-developing.asciidoc
This pull request adds basic documentation how to build the [machinekit/EMCApplication](https://github.com/machinekit/EMCApplication) binaries natively as Debian packages in Docker container (for native and foreign architectures) and as a RIP native build.
Requested in issue machinekit/EMCApplication#3.
> Add documentation for Machinekit EMCApplication project

- docs/developing/emcapplication-developing.asciidoc
- docs/getting-started/installing-packages.asciidoc
This pull request adds note about new `cloudsmith.io/~machinekit` based channels to the documentation in place where user is advised to install old `deb.machinekit.io` based ones. 
This is partially solving issue described in #321 (and is actually putting _lipstick on pig_ - but it will do for now).
> Note about old and new Debian package channels

- .github/workflows/build-preview-pages.yaml
- .github/workflows/ping-remote-repository.yaml
This pull request solves issue #325.
GitHub [deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) the old `set-env` command format for setting of environment variables. Instead, the new config files has to be used.
This is the second part of the solution, first is the pull request machinekit/machinekit.github.io#65 (which should be merged first before this PR).
> Use new format for setting of ENV variables
